=== Apress/pro-apache-xml/1590596412-1/Chapter02/Ch02/src/XMLBeans-Example/schemas/Orders.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace = "http://www.apress.com/apacheXML"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	attributeFormDefault="unqualified" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Orders">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Customer">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="StockSymbol">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="Quantity" type="xs:unsignedByte" />
                    <xs:element name="TradeType" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Apress/pro-apache-xml/1590596412-1/Chapter02/Ch02/src/Orders.xml
<?xml version="1.0" encoding="utf-8" ?>
<Orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="C:\xmlbeans-2.0.0\test\Orders.xsd"
>
  <Customer ID="C001">
    <StockSymbol>
      MSFT
      <Quantity>
        200
      </Quantity>
      <TradeType>
        B
      </TradeType>
    </StockSymbol>
  </Customer>
  <Customer ID="C002">
    <StockSymbol>
      IBM
      <Quantity>
        50
      </Quantity>
      <TradeType>
        S
      </TradeType>
    </StockSymbol>
  </Customer>
  <Customer ID="C003">
    <StockSymbol>
      MSFT
      <Quantity>
        100
      </Quantity>
      <TradeType>
        B
      </TradeType>
    </StockSymbol>
  </Customer>
  <Customer ID="C004">
    <StockSymbol>
      MSFT
      <Quantity>
        150
      </Quantity>
      <TradeType>
        B
      </TradeType>
    </StockSymbol>
    <StockSymbol>
      IBM
      <Quantity>
        150
      </Quantity>
      <TradeType>
        S
      </TradeType>
    </StockSymbol>
  </Customer>
  <Customer ID="C005">
    <StockSymbol>
      MSFT
      <Quantity>
        100
      </Quantity>
      <TradeType>
        B
      </TradeType>
    </StockSymbol>
  </Customer>
  <Customer ID="C006">
    <StockSymbol>
      MSFT
      <Quantity>
        50
      </Quantity>
      <TradeType>
        S
      </TradeType>
    </StockSymbol>
    <StockSymbol>
      IBM
      <Quantity>
        50
      </Quantity>
      <TradeType>
        S
      </TradeType>
    </StockSymbol>
  </Customer>
</Orders>
